/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************

*/
#include <main.h>
#include <stm32f303xx.h>


#define RCC_CFGR_REG_OFFSET		    0x04
#define RCC_CFGR_REG_ADDR		    RCC_BASEADDR + RCC_CFGR_REG_OFFSET




int main(void)
{

	uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;
	// 1. Configure RCC_CFGR register
	*pRccCfgrReg |= (0x05 << 24);
	// a) Enable the perpheral clock for GPIOA Peripheral


	while(1);
};

