/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************

*/
#include <main.h>
#include <stm32f303xx.h>
#include <String.h>
#include <usart.h>


char msg[1024] = "UART_Tx Testing ... \n\r";

void delay(void)
{
	for(uint32_t i = 0; i < 500000; i++);
}




void GPIOLEDsetup()
{
	   GPIO_Handle_t GPIO_LED;

	   memset(&GPIO_LED,0, sizeof(GPIO_LED));
	   GPIO_LED.pGPIOx = GPIOA;
	   GPIO_LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN5;
	   GPIO_LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	   GPIO_LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	   GPIO_LED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	   GPIO_LED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	   GPIO_PeriClockControl(GPIOA, ENABLE);
	   GPIO_Init(&GPIO_LED);
}


void GPIOButtonsetup()
{
	GPIO_Handle_t GPIO_USER_BUTTON;

	// local will contain garbage value when Output type is not assigned
	memset(&GPIO_USER_BUTTON,0, sizeof(GPIO_USER_BUTTON));

	GPIO_USER_BUTTON.pGPIOx = GPIOC;
	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN13;
	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU;
	GPIOC_PCLK_EN();
	GPIO_Init(&GPIO_USER_BUTTON);
}




USART_Handle_t USART2_handle;



void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN13);
	GPIO_ToggleOutputPin(GPIOA, GPIO_PIN5);
}

int main(void)
{
	USART2_GPIOInit();
	USART2_Init();





	while(1)
	{
		USART_SendData(&USART2_handle, (uint8_t*)msg, strlen(msg));
	}


	return 0;






};

